version: '3'

services:
  
  postgres:
    container_name: main-DB
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backup.tar:/backup/backup.tar
      - ./restore.sh:/docker-entrypoint-initdb.d/restore.sh
    restart: always


  redis:
    container_name: redis-cache
    image: redis:latest
    ports:
      - "6379:6379"

  main:
    container_name: main-api
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    command: pnpm run dev
    depends_on:
      - postgres
      # - redis
    restart: always


volumes:
  db_data: